<!doctype html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ReaktifRadar — Reaktif enerjiyi görün, zamanında harekete geçin</title>
    <meta name="description" content="Tesisatlarınızın endüktif ve kapasitif oranlarını tek panelden izleyin. Saatlik, günlük ve aylık analizlerle eşik aşımlarını görün; e-posta ve Telegram raporlarıyla takipte kalın.">
    <meta name="theme-color" content="#f5f6f0">
    <meta property="og:title" content="ReaktifRadar — Enerjiniz radarınızda.">
    <meta property="og:description" content="Reaktif enerji oranlarını takip edin. Eşik aşımlarını görün. Tesisatlarınızı tek bir yerden yönetin.">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="tr_TR">
    <link rel="stylesheet" href="{{ asset('css/landing.css') }}">
</head>
<body>
<a class="skip" href="#main">İçeriğe geç</a>
<header class="header wrap">
    <a href="{{ url('/') }}" class="brand" aria-label="ReaktifRadar ana sayfa"><span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 32 32"><circle cx="16" cy="16" r="12"/><circle cx="16" cy="16" r="6"/><path d="M16 16 25 7"/><circle class="blip" cx="24" cy="8" r="3"/></svg></span>Reaktif<span>Radar</span></a>
    <nav aria-label="Ana menü"><a href="#ozellikler">Neler sunuyor?</a><a href="#nasil-calisir">Nasıl çalışır?</a><a href="#sorular">Sorular</a></nav>
    <div class="header-actions"><a class="login" href="{{ route('enerjisa.login') }}">Giriş yap</a><a class="button small" href="{{ route('enerjisa.register') }}">Hemen başla <span aria-hidden="true">↗</span></a></div>
</header>
<main id="main">
<section class="hero wrap">
    <div class="hero-copy">
        <div class="eyebrow"><span class="live-dot"></span> ENERJİ TAKİBİNDE YENİ BİR BAKIŞ</div>
        <h1>Enerjiniz<br><span class="underlined">radarınızda.</span><br>Kontrol sizde.</h1>
        <p class="hero-description">Endüktif ve kapasitif oranları takip edin, eşik aşımlarını görün. Tesisatlarınızın reaktif enerji verisini anlaşılır bir aksiyon planına dönüştürün.</p>
        <div class="hero-actions"><a class="button" href="{{ route('enerjisa.register') }}">Tesisatımı takip etmek istiyorum <span aria-hidden="true">↗</span></a><a class="text-link" href="#panel">Paneli keşfet <span aria-hidden="true">↓</span></a></div>
        <div class="hero-footnote"><span aria-hidden="true">✓</span> Tek panelde tüm tesisatlarınız <span class="separator">/</span> E-posta & Telegram</div>
    </div>
    <div class="hero-visual" id="panel">
        <div class="visual-label"><span>DAHA NET VERİ. DAHA DOĞRU AKSİYON.</span><span>01 / 03</span></div>
        <div class="dashboard">
            <div class="dashboard-head"><div><span class="mini-eyebrow">TESİSAT GÖRÜNÜMÜ</span><h2>Enerjiye yakından bakın.</h2></div><span class="dashboard-symbol" aria-hidden="true">↗</span></div>
            <div class="facility"><div class="facility-icon" aria-hidden="true">▥</div><div><strong>Merkez üretim tesisi</strong><span>Reaktif enerji analizi</span></div><span class="demo-tag">ÖRNEK VERİ</span></div>
            <div class="preview-periods" role="group" aria-label="Örnek analiz dönemi"><button type="button" data-period="hourly" aria-pressed="false">Saatlik</button><button type="button" data-period="daily" aria-pressed="true" class="active">Günlük</button><button type="button" data-period="monthly" aria-pressed="false">Aylık</button><span>Örnek görünüm</span></div>
            <div class="ratio-grid" aria-live="polite"><div class="ratio-card"><div class="ratio-title">Endüktif oran <span aria-hidden="true">↗</span></div><div class="ratio-value" id="inductive-value">%18,4</div><div class="meter"><i id="inductive-bar" style="width:73.6%"></i><b style="left:80%"></b></div><div class="ratio-caption"><span id="inductive-status">Eşik içinde</span><span>Eşik %20</span></div></div><div class="ratio-card"><div class="ratio-title">Kapasitif oran <span aria-hidden="true">↗</span></div><div class="ratio-value" id="capacitive-value">%8,2</div><div class="meter"><i id="capacitive-bar" style="width:32.8%"></i><b style="left:60%"></b></div><div class="ratio-caption"><span id="capacitive-status">Eşik içinde</span><span>Eşik %15</span></div></div></div>
            <div class="chart-head"><span>Endüktif oran değişimi</span><span><i></i> Ölçüm <b></b> Eşik</span></div>
            <svg class="chart" viewBox="0 0 440 132" role="img" aria-label="Örnek endüktif oran grafiği; kesikli çizgi yüzde 20 eşiğini gösterir"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#d4f86b" stop-opacity=".25"/><stop offset="100%" stop-color="#d4f86b" stop-opacity="0"/></linearGradient></defs><path class="gridlines" d="M0 25H440M0 66H440M0 108H440"/><path d="M0 38H440" class="threshold"/><text x="411" y="29">%20</text><path id="chart-area" d="M0 94L44 83L88 89L132 65L176 78L220 60L264 72L308 52L352 62L396 44L440 49V132H0Z" fill="url(#chart-fill)"/><path id="chart-line" d="M0 94L44 83L88 89L132 65L176 78L220 60L264 72L308 52L352 62L396 44L440 49" class="trend"/></svg>
            <div class="chart-axis"><span id="axis-start">00:00</span><span id="axis-middle">12:00</span><span id="axis-end">23:00</span></div>
            <div class="dashboard-bottom"><span><i class="live-dot"></i> Son alınan ölçümle hesaplandı</span><span>İstanbul saati</span></div>
        </div>
        <div class="notification"><div class="notification-icon" aria-hidden="true">↗</div><div><strong>Takip sizden, hatırlatma bizden.</strong><p>Günlük veya haftalık durum raporunuz hazır.</p></div><span class="notification-check" aria-hidden="true">✓</span></div>
        <p class="preview-note">Etkileşimli ürün önizlemesi · Gösterilen değerler örnektir.</p>
    </div>
</section>
<section class="integration wrap" aria-label="Entegrasyon ve kullanım alanları"><div><span class="tiny-label">VERİ KAYNAĞI</span><strong>Başkent EDAŞ <span>MDM entegrasyonu</span></strong></div><p>Üretim tesisleri <span>✳</span> İşletmeler <span>✳</span> Teknik ekipler</p></section>
<section class="benefits wrap section" id="ozellikler">
    <div class="section-heading"><div><div class="eyebrow">DAHA AZ TABLO. DAHA FAZLA GÖRÜNÜRLÜK.</div><h2>Enerji verinizi anlayın.<br><span>İşinize odaklanın.</span></h2></div><p>Dağınık kayıtlar ve elle yapılan hesaplar yerine, neye bakmanız gerektiğini gösteren bir çalışma alanı.</p></div>
    <div class="benefit-grid">
        <article class="benefit-card large"><div class="card-top"><span class="feature-icon" aria-hidden="true">⌁</span><span class="card-index">01 / ANALİZ</span></div><h3>Rakamların arkasındaki<br>durumu görün.</h3><p>Saatlik, günlük ve aylık karşılaştırmalarla endüktif ve kapasitif oranlarınızı inceleyin. Eşik üzerindeki değerleri renkli vurgularla fark edin.</p><div class="analysis-mini"><div><span>ENDÜKTİF</span><strong>%22,6 <small>Eşik aşımı ↗</small></strong></div><div class="mini-track"><span></span><i></i></div><div class="mini-labels"><span>Örnek ölçüm</span><span>Eşik: %20</span></div></div></article>
        <article class="benefit-card"><div class="card-top"><span class="feature-icon" aria-hidden="true">↗</span><span class="card-index">02 / BİLDİRİM</span></div><h3>Panele girmeden<br>takipte kalın.</h3><p>Tesisat bazında günlük veya haftalık e-posta ve Telegram raporları alın. İsterseniz sorun olmadığında da bilgi gelsin.</p><div class="channel-pills"><span><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 6 9 7 9-7"/></svg>E-posta</span><span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 11 18-7-4 17-6-6-4 2 1-5 10-6-7 9"/></svg>Telegram</span></div></article>
        <article class="benefit-card"><div class="card-top"><span class="feature-icon" aria-hidden="true">▦</span><span class="card-index">03 / YÖNETİM</span></div><h3>Birden fazla tesisat.<br>Tek bir bakış.</h3><p>Tesisatlar arasında kolayca geçiş yapın. Tarih aralığını seçin, geçmiş ölçümleri karşılaştırın ve analiz sonuçlarını CSV olarak indirin.</p><div class="site-list"><span><i></i> Merkez tesis <b>↗</b></span><span><i></i> İkinci tesis <b>↗</b></span></div></article>
    </div>
</section>
<section class="workflow" id="nasil-calisir"><div class="wrap section"><div class="workflow-heading"><div><div class="eyebrow">KARMAŞIK KURULUMLARA GEREK YOK</div><h2>Üç adımda<br>radarınızı açın.</h2></div><a class="button light" href="{{ route('enerjisa.register') }}">İlk adımı at <span aria-hidden="true">↗</span></a></div><div class="steps-grid"><article><span class="step-number">01</span><h3>Çalışma alanınızı oluşturun.</h3><p>Firma bilgilerinizle hesabınızı açın. Tesisatlarınızı takip edeceğiniz size ait alana giriş yapın.</p></article><article><span class="step-number">02</span><h3>Enerji verinizi bağlayın.</h3><p>Başkent EDAŞ MDM erişim bilgilerinizi ekleyin ve yetkili olduğunuz tesisatları getirin.</p></article><article><span class="step-number">03</span><h3>Analiz edin, takipte kalın.</h3><p>Oranları inceleyin. Alıcı adresinizi ve bildirim sıklığını seçerek düzenli raporlarınızı yapılandırın.</p></article></div><div class="workflow-note"><span aria-hidden="true">↳</span> Başlamak için yetkili bir Başkent EDAŞ MDM servis hesabınız olmalıdır.</div></div></section>
<section class="clarity wrap section"><div class="clarity-visual" aria-hidden="true"><div class="radar-orbit orbit-one"></div><div class="radar-orbit orbit-two"></div><div class="radar-orbit orbit-three"></div><div class="radar-cross horizontal"></div><div class="radar-cross vertical"></div><div class="radar-sweep"></div><div class="radar-center">R</div><div class="radar-point point-one"></div><div class="radar-point point-two"></div><div class="radar-caption"><span class="live-dot"></span> DAHA GÖRÜNÜR. DAHA YÖNETİLEBİLİR.</div></div><div class="clarity-copy"><div class="eyebrow">NEYİ BİLDİĞİNİZİ BİLİN</div><h2>Net sonuçlar.<br><span>Şeffaf hesaplama.</span></h2><p>Bir oran kadar, o oranın hangi ölçümlerden hesaplandığı da önemlidir. ReaktifRadar verinin sınırlarını görünür kılar.</p><ul><li><span>↗</span><div><strong>Son ölçüme kadar hesaplama</strong><p>Son gün için ertesi günün kaydını beklemeden, alınabilen son ölçümle analiz.</p></div></li><li><span>◷</span><div><strong>Eksik veri gizlenmez</strong><p>Kısmi dönemler ve hesaplanamayan değerler açıkça belirtilir.</p></div></li><li><span>↻</span><div><strong>Verinizin tarihini görün</strong><p>Eski ölçümlerde güncelleme hatırlatmasıyla kontrol sizde kalır.</p></div></li></ul></div></section>
<section class="faq wrap section" id="sorular"><div><div class="eyebrow">AKLINIZDAKİLER</div><h2>Başlamadan<br>önce.</h2><p>ReaktifRadar hakkında<br>birkaç kısa cevap.</p></div><div class="faq-list"><details open><summary>Hangi tesisatları takip edebilirim?<span aria-hidden="true">+</span></summary><p>Mevcut entegrasyon Başkent EDAŞ MDM servisidir. Servis hesabınızın erişim yetkisi bulunan tesisatları takip edebilirsiniz. Servis erişimi ve gerekli IP izinleri veri sağlayıcı tarafından tanımlanmalıdır.</p></details><details><summary>Ek bir cihaz kurmam gerekiyor mu?<span aria-hidden="true">+</span></summary><p>ReaktifRadar için ek bir cihaz kurmanız gerekmez. Analizler, mevcut servis hesabınız üzerinden erişilebilen saatlik sayaç endekslerini kullanır.</p></details><details><summary>Bildirimleri nasıl alırım?<span aria-hidden="true">+</span></summary><p>Her tesisat için günlük veya haftalık sıklık seçebilirsiniz. E-posta adresinizi ekleyin ya da paneldeki bağlantı adımıyla Telegram'ı bağlayın. Sorun olmadığında da rapor gönderilmesini seçebilirsiniz.</p></details><details><summary>Veriler anlık mı güncelleniyor?<span aria-hidden="true">+</span></summary><p>Verinin güncelliği Başkent EDAŞ servisinin sunduğu kayıtlara bağlıdır. Son ölçüm zamanı panelde gösterilir. Bugünün verisi istenir; servis sunmuyorsa mevcut son ölçümler kullanılır. Dilediğinizde “Verileri yenile” ile yeniden sorgulayabilirsiniz.</p></details><details><summary>Panelde hangi eşikler kullanılıyor?<span aria-hidden="true">+</span></summary><p>Endüktif oran %20'nin, kapasitif oran %15'in üzerindeyse panel değeri vurgular. Oranlar, reaktif endeks farkının aktif endeks farkına bölünmesiyle hesaplanır. Bu gösterimler takip amaçlıdır; fatura veya ceza tutarı hesaplaması yapılmaz.</p></details></div></section>
<section class="cta wrap"><div><div class="eyebrow">ENERJİNİZİ GÖRÜNÜR KILIN</div><h2>Bir sonraki ölçümde,<br>kontrol sizde olsun.</h2><p>Tesisatlarınızı bağlayın. Oranlarınızı görün. Takipte kalın.</p></div><a class="button dark" href="{{ route('enerjisa.register') }}">ReaktifRadar’a başla <span aria-hidden="true">↗</span></a><svg class="cta-rings" viewBox="0 0 400 400" aria-hidden="true"><circle cx="300" cy="220" r="95"/><circle cx="300" cy="220" r="150"/><circle cx="300" cy="220" r="205"/></svg></section>
</main>
<footer class="wrap footer"><div class="footer-top"><a href="{{ url('/') }}" class="brand">Reaktif<span>Radar</span><span class="footer-dot" aria-hidden="true"></span></a><p>Enerjiyi anlayın. Kontrolü elinizde tutun.</p><a href="{{ route('enerjisa.login') }}">Panele giriş <span aria-hidden="true">↗</span></a></div><div class="footer-bottom"><span>© {{ date('Y') }} ReaktifRadar</span><span>Başkent EDAŞ / Enerjisa’dan bağımsız bir takip uygulamasıdır.</span><a href="#main">Yukarı dön ↑</a></div></footer>
<script src="{{ asset('js/landing.js') }}" defer></script>
</body>
</html>
