@extends('enerjisa.layout')
@section('title', 'Reaktif enerji analizi')
@section('content')
<style>
.reactive-heading{align-items:flex-start}.reactive-heading p{max-width:650px}.reactive-tabs{display:flex;gap:4px;background:#edf2f5;border-radius:10px;padding:4px;width:fit-content;margin:0 0 22px}.reactive-tabs label{margin:0;cursor:pointer}.reactive-tabs input{position:absolute;width:1px;height:1px;opacity:0;min-height:0}.reactive-tabs span{display:block;padding:9px 24px;border-radius:7px;color:var(--muted);font-size:13px}.reactive-tabs input:checked+span{background:white;color:var(--accent);box-shadow:0 1px 5px #102d3b15}.reactive-tabs input:focus-visible+span{outline:2px solid var(--accent)}.reactive-filters{display:grid;grid-template-columns:2fr 1.4fr 1fr 1fr;gap:16px}.reactive-filters .field{margin-bottom:14px}.reactive-toolbar{display:flex;justify-content:space-between;gap:20px;align-items:center;border-top:1px solid var(--line);padding-top:18px;margin-top:5px}.reactive-toolbar select{max-width:240px}.reactive-stats{grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.reactive-stats .card{padding:20px}.reactive-stat-alert{border-top:3px solid #db6554}.reactive-stat-muted{border-top:3px solid #bdcad4}.reactive-stat-ok{border-top:3px solid #198f84}.reactive-table th{position:sticky;top:0;z-index:1}.reactive-table-wrap{max-height:640px}.reactive-table td{vertical-align:top;font-variant-numeric:tabular-nums}.reactive-table td:first-child{min-width:175px}.reactive-table .exceeded{background:#fff0eb;color:#ab392b;font-weight:750;border-radius:5px;padding:5px 9px;display:inline-block}.reactive-table .within{background:#eaf6ef;color:#23714f;border-radius:5px;padding:5px 9px;display:inline-block}.reactive-table .row-alert td:first-child{border-left:3px solid #dc7256}.reactive-table .row-invalid{background:#fafbfc}.reactive-small{font-size:11px;color:var(--muted);margin-top:5px;white-space:normal;max-width:240px}.reactive-neutral{background:#eff2f5;color:#586b7b}.reactive-warning{background:#fff5d9;color:#80621d}.reactive-boundaries{font-size:12px;line-height:1.8;min-width:165px}.reactive-key{display:flex;gap:20px;flex-wrap:wrap;font-size:12px;color:var(--muted);margin:12px 0}.reactive-note{font-size:12px;color:var(--muted)}.reactive-formulas{display:grid;grid-template-columns:1fr 1fr;gap:25px;margin-top:15px}.reactive-formula{background:#f5f8fa;padding:16px;border-radius:9px;font-size:13px}.reactive-formula strong{display:block;margin-bottom:8px}.reactive-detail td{background:#f8fafc}.reactive-details summary{font-size:12px}.reactive-details{margin:4px 0 0}.reactive-details table td{padding:6px;font-size:11px}.reactive-details table{margin-top:10px}.reactive-status-summary{color:var(--muted);font-size:12px}.reactive-empty{padding:55px 25px}.reactive-alert-dot{display:inline-block;height:8px;width:8px;border-radius:50%;background:#d96553;margin-right:6px}
@media(max-width:1100px){.reactive-filters{grid-template-columns:1fr 1fr}.reactive-stats{grid-template-columns:1fr 1fr}}@media(max-width:700px){.reactive-filters,.reactive-formulas{grid-template-columns:1fr}.reactive-stats{gap:10px}.reactive-stats .metric{font-size:25px}.reactive-stats .card{padding:15px;margin-bottom:10px}.reactive-toolbar{align-items:stretch;flex-direction:column}.reactive-toolbar select{max-width:none}.reactive-tabs{width:100%}.reactive-tabs label{flex:1;text-align:center}.reactive-tabs span{padding:9px 12px}}
</style>
<div class="heading reactive-heading"><div><div class="eyebrow">REAKTİF ENERJİ TAKİBİ</div><h1>Endüktif & kapasitif analiz</h1><p class="muted">Tüketim farklarını inceleyin, belirlediğiniz eşikleri aşan dönemleri görün.</p></div><div class="actions">@if($lastReading)<a class="button" href="{{ route('enerjisa.reactive.download', collect($filters)->except('page')->all()) }}">CSV indir ↓</a>@endif<button class="secondary" type="submit" form="reactive-form" name="refresh" value="1">Verileri yenile ↻</button></div></div>
<form id="reactive-form" method="post" action="{{ route('enerjisa.reactive.calculate') }}" class="card" data-loading>@csrf
<div class="reactive-tabs" role="group" aria-label="Hesaplama dönemi">@foreach(['hourly' => 'Saatlik', 'daily' => 'Günlük', 'monthly' => 'Aylık'] as $key => $label)<label><input type="radio" name="period" value="{{ $key }}" @checked($filters['period'] === $key)><span>{{ $label }}</span></label>@endforeach</div>
<div class="reactive-filters">
<div class="field"><label for="reactive-installation">Tesisat</label><select id="reactive-installation" name="installation" required><option value="">Tesisat seçin</option>@foreach($installations as $number => $label)<option value="{{ $number }}" @selected((string)$number === $filters['installation'])>{{ $label }}</option>@endforeach</select></div>
<div class="field"><label for="reactive-meter">Sayaç</label><select name="meter" id="reactive-meter"><option value="">Otomatik seç</option>@foreach($meters as $number => $readings)<option value="{{ $number }}" @selected((string)$number === $filters['meter'])>{{ $number === 'unknown' ? 'Sayaç bilgisi olmayan kayıtlar' : $number }}</option>@endforeach</select></div>
<div class="field"><label for="reactive-start">Başlangıç</label><input id="reactive-start" type="date" name="start" value="{{ $filters['start'] }}" max="{{ now('Europe/Istanbul')->format('Y-m-d') }}" required></div>
<div class="field"><label for="reactive-end">Bitiş</label><input id="reactive-end" type="date" name="end" value="{{ $filters['end'] }}" max="{{ now('Europe/Istanbul')->format('Y-m-d') }}" required></div>
</div>
<div class="reactive-toolbar"><div class="reactive-note" id="period-help">Saatlik ve günlük hesaplar tam saat sınırlarını kullanır. Aylık görünüm seçilen tarihlerin ait olduğu ayları kapsar.</div><div class="actions"><label class="muted" for="reactive-status" style="margin:0">Göster</label><select name="status" id="reactive-status">@foreach(['all' => 'Tüm dönemler', 'alert' => 'Yalnızca eşik aşımı', 'invalid' => 'Hesaplanamayanlar'] as $key => $label)<option value="{{ $key }}" @selected($filters['status'] === $key)>{{ $label }}</option>@endforeach</select><button type="submit">Hesapla →</button></div></div>
<p class="reactive-note" style="margin-top:14px;margin-bottom:0">Hesapla ile seçilen dönem için daha önce alınmamış veriler otomatik getirilir. Bugünün verisi de denenir; servis izin vermiyorsa son alınabilen ölçümler kullanılır. Eksik dönen kayıtları tekrar almak için “Verileri yenile”yi kullanın.</p>
</form>
@if($filters['installation'])<section class="card"><div class="eyebrow">TESİSAT SAHİBİ</div><h2 style="margin-top:8px">{{ $owner ?: 'Tesisat sahibi bilgisi bulunmuyor' }}</h2><div class="muted">Tesisat {{ $filters['installation'] }}</div></section>@endif
@if(!$installations)<div class="notice">Önce <a href="{{ route('enerjisa.installations') }}">tesisat listenizi getirin</a>.</div>@endif
@if(count($meters) > 1)<div class="notice">Bu tesisatta birden fazla sayaç serisi var. Her sayaç ayrı hesaplanır; yukarıdan incelemek istediğiniz sayacı seçin.</div>@endif
@if($loaded['invalidDates'])<div class="notice">{{ $loaded['invalidDates'] }} kaydın tarihi okunamadığı için hesaplamaya alınmadı. İlgili sorgunun JSON yanıtını kontrol edin.</div>@endif
@if(!$lastReading)
<section class="card empty reactive-empty"><div class="empty-symbol">⌁</div><h2>Bu seçim için saatlik endeks kaydı yok</h2><p class="muted">Oranlar aktif, endüktif ve kapasitif sayaç endekslerinden hesaplanır.<br>Tesisat ve tarihleri seçip “Hesapla”ya basın; gerekli veriler otomatik alınır.</p><button type="submit" form="reactive-form">Verileri getir ve hesapla →</button></section>
@else
@if($lastReading->time->lessThan(now('Europe/Istanbul')->startOfDay()))
<div class="notice reactive-warning" role="status"><strong>Geçmiş tarihli veriler kullanılıyor</strong><p>Bu seçimdeki son ölçüm <strong>{{ $lastReading->time->format('d.m.Y H:i') }}</strong> tarihine ait. Daha yeni kayıtları kontrol etmek için <strong>“Verileri yenile”</strong> düğmesine basın. Güncel dönemi incelemek istiyorsanız bitiş tarihini de bugüne alın.</p><button type="submit" form="reactive-form" name="refresh" value="1">Verileri yenile ↻</button></div>
@endif
<div class="grid reactive-stats"><div class="card"><div class="metric-label">İNCELENEN DÖNEM</div><div class="metric">{{ $summary['total'] }}</div><span class="reactive-note">Seçilen sayaç ve tarih aralığı</span></div><div class="card reactive-stat-ok"><div class="metric-label">HESAPLANAN</div><div class="metric">{{ $summary['calculated'] }}</div><span class="reactive-note">Geçerli endeks farkları</span></div><div class="card reactive-stat-alert"><div class="metric-label">EŞİK AŞIMI</div><div class="metric">{{ $summary['alerts'] }}</div><span class="reactive-note">En az bir oran sınırın üzerinde</span></div><div class="card reactive-stat-muted"><div class="metric-label">HESAPLANAMAYAN</div><div class="metric">{{ $summary['invalid'] }}</div><span class="reactive-note">Eksik veri, sıfır tüketim veya sayaç sorunu</span></div></div>
<section class="card"><div class="heading" style="margin-bottom:10px"><div><h2>Dönem karşılaştırmaları</h2><div class="reactive-status-summary">Tesisat {{ $filters['installation'] }} · Sayaç {{ $filters['meter'] === 'unknown' ? 'bilgisi yok' : $filters['meter'] }}</div></div><div class="reactive-note">Son ölçüm: <strong>{{ $lastReading->time->format('d.m.Y H:i') }}</strong><br>Son veri sorgusu: {{ $loaded['lastQuery'] }}</div></div>
<div class="reactive-key"><span><i class="reactive-alert-dot"></i>Endüktif &gt; %20</span><span><i class="reactive-alert-dot"></i>Kapasitif &gt; %15</span><span>Sınıra eşit değerler aşım sayılmaz.</span></div>
@if($rows->isEmpty())<div class="empty"><h3>Bu filtreye uyan dönem yok</h3><p class="muted">Göster filtresini “Tüm dönemler” olarak değiştirip yeniden hesaplayın.</p></div>
@else
<div class="table-wrap reactive-table-wrap"><table class="reactive-table"><thead><tr><th>DÖNEM / DURUM</th><th>ÖLÇÜM ARALIĞI</th><th>AKTİF FARK<br>kWh</th><th>ENDÜKTİF FARK<br>kVArh</th><th>KAPASİTİF FARK<br>kVArh</th><th>ENDÜKTİF ORAN<br>Eşik %20</th><th>KAPASİTİF ORAN<br>Eşik %15</th></tr></thead><tbody>
@foreach($rows as $row)
<tr class="{{ $row['status'] === 'alert' ? 'row-alert' : (!in_array($row['status'], ['ok', 'alert']) ? 'row-invalid' : '') }}">
<td><strong>{{ $row['label'] }}</strong><br><span class="status {{ $row['status'] === 'alert' ? 'error' : ($row['status'] === 'ok' ? '' : 'reactive-neutral') }}">{{ $row['message'] }}</span>@if($row['partial'])<div class="reactive-small">Kısmi dönem · son gelen ölçüme kadar</div>@endif
<details class="reactive-details"><summary>Endeks ayrıntısı</summary><table><tr><th></th><th>İlk</th><th>Son</th></tr>@foreach(['active' => 'Aktif', 'inductive' => 'Endüktif', 'capacitive' => 'Kapasitif'] as $field => $label)<tr><td>{{ $label }}</td><td>{{ $row['first']?->$field ?? '—' }}</td><td>{{ $row['last']?->$field ?? '—' }}</td></tr>@endforeach</table><div class="reactive-small">Kaynak sorgular: {{ $row['first']?->queryId ?? '—' }} / {{ $row['last']?->queryId ?? '—' }}</div></details></td>
<td class="reactive-boundaries">{{ $row['first']?->time->format('d.m.Y H:i') ?? 'Başlangıç kaydı yok' }}<br><span class="muted">↓</span><br>{{ $row['last']?->time->format('d.m.Y H:i') ?? 'Bitiş kaydı yok' }}</td>
@foreach(['activeDelta', 'inductiveDelta', 'capacitiveDelta'] as $field)<td>{{ $row[$field] !== null ? number_format((float)$row[$field], 3, ',', '.') : '—' }}</td>@endforeach
@foreach(['inductiveRatio' => 'inductiveAlert', 'capacitiveRatio' => 'capacitiveAlert'] as $field => $alert)<td>@if($row[$field] !== null)<span class="{{ $row[$alert] ? 'exceeded' : 'within' }}">%{{ number_format((float)$row[$field], 3, ',', '.') }}</span>@if($row[$alert])<div class="reactive-small">Eşik üzerinde</div>@endif @else<span class="muted">—</span>@endif</td>@endforeach
</tr>
@endforeach
</tbody></table></div>@include('enerjisa.pagination', ['paginator' => $rows])
@endif
</section>
@endif
<section class="card"><h2>Hesaplama yöntemi</h2><div class="reactive-formulas"><div class="reactive-formula"><strong>Endüktif oran</strong>(Son endüktif − ilk endüktif) ÷ (Son aktif − ilk aktif) × 100</div><div class="reactive-formula"><strong>Kapasitif oran</strong>(Son kapasitif − ilk kapasitif) ÷ (Son aktif − ilk aktif) × 100</div></div><div class="steps"><div><strong>Saatlik</strong><p>00:00 → 01:00 gibi ardışık tam saat endeksleri karşılaştırılır. Eksik saatler birleştirilmez.</p></div><div><strong>Günlük</strong><p>Günün 00:00 kaydı ile ertesi günün 00:00 kaydı karşılaştırılır. Son ölçüm gününde kapanış kaydı yoksa o günün son gelen ölçümü kullanılır ve kısmi gün olarak gösterilir.</p></div><div><strong>Aylık</strong><p>Ayın ilk günü 00:00 ile o ay içindeki son gelen ölçüm karşılaştırılır. İçinde bulunduğumuz ay devam eden dönemdir. Geçmiş ayın son saat kaydı yoksa sonuç kısmi olarak işaretlenir.</p></div></div><p class="reactive-note" style="margin-top:18px">Veriler kayıtlı saatlik endeks sorgularından alınır; uzun tarih aralıkları otomatik olarak aylık sorgulara bölünür. Saat dilimi: İstanbul. Oranların ortalaması alınmaz; dönemlerin endeks farkları kullanılır. Aktif fark sıfırsa, sayaç endeksi azalmışsa veya gerekli ölçüm yoksa oran hesaplanmaz. Eşikler sizin belirlediğiniz %20 / %15 değerleridir. Düzenli raporları Bildirimler bölümünden yapılandırabilirsiniz.</p></section>
@endsection
@push('scripts')
<script>
document.getElementById('reactive-installation').addEventListener('change', () => { document.getElementById('reactive-meter').innerHTML = '<option value="">Otomatik seç</option>'; });
</script>
@endpush
